apiVersion: v1
kind: Namespace
metadata:
  name: backstage

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-k8s
  namespace: backstage

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-read-poddelete
rules:
  # Core read resources
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - services
      - endpoints
      - configmaps
      - namespaces
      - events
      - nodes
      - limitranges
      - resourcequotas
    verbs: ["get", "list", "watch"]

  # Allow pod deletion ONLY (Backstage podDelete)
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["delete"]

  # Apps workloads
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs: ["get", "list", "watch"]

  # Batch jobs
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]

  # Metrics-API
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
      - nodes
    verbs: ["get", "list", "watch"]

  # Autoscaling (HPA)
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch"]

  # Networking (Ingress)
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-read-poddelete-binding
subjects:
  - kind: ServiceAccount
    name: backstage-k8s
    namespace: backstage
roleRef:
  kind: ClusterRole
  name: backstage-read-poddelete
  apiGroup: rbac.authorization.k8s.io